apiVersion: batch/v1
kind: Job
metadata:
  name: stwtch-job
spec:
  template:
    spec:
      containers:
      - name: stwtch-job
        image: yash5090/stwtch:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
